prompt --application/pages/page_00167
begin
--   Manifest
--     PAGE: 00167
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>7945143549875994
,p_default_application_id=>103
,p_default_id_offset=>25186177142438240
,p_default_owner=>'WKSP_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>167
,p_name=>'Report Summary'
,p_alias=>'REPORT_SUMMARY'
,p_step_title=>'Report Summary'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'OFF'
,p_javascript_file_urls=>'#APP_FILES#gridReportSummary#MIN#.js'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
' ',
'   ',
'   ',
'    window.tailwind = {',
'        config: {',
'            darkMode: "class",',
'            theme: {',
'                extend: {',
'                    colors: {',
'                        current: "currentColor"',
'                    }',
'                }',
'            }',
'        }',
'    };',
'',
'',
'',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
' ',
'/* .container {',
'  /* display: flex; */',
'  /* Add other flex properties as needed for the layout of its direct children (e.g., .row) */',
'  /* flex-direction: row; */ /* or column */',
'  /* justify-content: center; */ /* or space-between, flex-start, etc. */',
'  /* align-items: center; */ /* or flex-start, stretch, etc. */',
'  /* gap: 10px; */ /* for spacing between items */',
'/* } */ ',
'/* MAIN DARK-MODE OVERRIDES */',
'html.dark .my-dashboard-scope {',
'    --bg-color: #1a202c;',
'    --text-color: #e2e8f0;',
'    --card-bg: #2d3748;',
'    --border-color: #4a5568;',
'    --accent-color: #63b3ed;',
'    --scrollbar-thumb: #4a5568;',
'    --scrollbar-track: #2d3748;',
'}',
'',
'/* Apply dark mode background + text globally */',
'html.dark .my-dashboard-scope body,',
'html.dark .my-dashboard-scope {',
'    /* --text-color: #000000;  */',
'    background-color: var(--bg-color) !important; ',
'    color: var(--text-color) !important;',
'}',
'',
'/* Cards (your actual dashboard widgets) */',
'html.dark .my-dashboard-scope .table-card {',
'    background-color: var(--card-bg) !important;',
'    border-color: var(--border-color) !important;',
'}',
'',
'/* Table preview backgrounds */',
'html.dark .my-dashboard-scope .preview-table thead {',
'    background-color: #374151 !important; /* darker header */',
'}',
'',
'html.dark .my-dashboard-scope .preview-table tbody tr:hover {',
'    background-color: rgba(255,255,255,0.05) !important;',
'}',
'',
'',
'/* Modal background */',
'html.dark #dataModal .modal-content {',
'    background-color: var(--card-bg) !important;',
'    color: var(--text-color) !important;',
'}',
'',
'/* Scrollbars */',
'html.dark .my-dashboard-scope .custom-scrollbar::-webkit-scrollbar-thumb {',
'    background-color: var(--scrollbar-thumb) !important;',
'}',
'html.dark .my-dashboard-scope .custom-scrollbar::-webkit-scrollbar-track {',
'    background-color: var(--scrollbar-track) !important;',
'}',
'',
' ',
' /* LIGHT MODE (default) */',
' ',
'.my-dashboard-scope {',
'    --bg-color: #ffffff;',
'    --text-color: #1f2937;',
'    --card-bg: #ffffff;',
'    --border-color: #e5e7eb;',
'    --accent-color: #2563eb;',
'    --scrollbar-thumb: #cbd5e1;',
'    --scrollbar-track: #f1f5f9;',
'}',
'',
'/* Apply to entire dashboard */',
'.my-dashboard-scope,',
'.my-dashboard-scope body {',
'    background-color: var(--bg-color) !important;',
'    color: var(--text-color) !important;',
'}',
'',
'/* Cards */',
'.my-dashboard-scope .table-card {',
'    background-color: var(--card-bg) !important;',
'    border-color: var(--border-color) !important; ',
'}',
'',
'',
'',
'/* Example: elements inside your scope reacting to APEX dark mode */',
'html.dark .my-dashboard-scope .card {',
'    background-color: rgb(31 41 55 / var(--tw-bg-opacity)); /* slate-800 */',
'    color: #f8fafc; /* slate-50 */',
'}',
'',
'html.dark .my-dashboard-scope header {',
'    background: #1f2937; /* slate-800 */',
'}',
'',
'  /* Tailwind CSS Core */',
'       .my-dashboard-scope *, ',
'.my-dashboard-scope *::before, ',
'.my-dashboard-scope *::after {',
'    box-sizing: border-box;',
'}',
'       .my-dashboard-scope html{line-height:1.5;-webkit-text-size-adjust:100%;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif;font-feature-settings:normal;font-variation-s'
||'ettings:normal}',
'       .my-dashboard-scope body{margin:0;line-height:inherit}',
'        .my-dashboard-scope .hidden{display:none}',
'        .my-dashboard-scope .flex{display:flex}',
'        .my-dashboard-scope .flex-col{flex-direction:column}',
'        .my-dashboard-scope .flex-row{flex-direction:row}',
'        .my-dashboard-scope .relative{position:relative}',
'        .my-dashboard-scope .absolute{position:absolute}',
'        .my-dashboard-scope .sticky{position:sticky}',
'        .my-dashboard-scope .fixed{position:fixed}',
'        .my-dashboard-scope .top-0{top:0}',
'        .my-dashboard-scope .right-0{right:0}',
'        .my-dashboard-scope .right-4{right:1rem}',
'        .my-dashboard-scope .bottom-4{bottom:1rem}',
'        .my-dashboard-scope .z-10{z-index:10}',
'        .my-dashboard-scope .z-40{z-index:40}',
'        .my-dashboard-scope .z-50{z-index:50}',
'        .my-dashboard-scope .m-0{margin:0}',
'        .my-dashboard-scope .mt-2{margin-top:0.5rem}',
'        .my-dashboard-scope .mt-3{margin-top:0.75rem}',
'        .my-dashboard-scope .mt-4{margin-top:1rem;  --text-color: #000000;  }',
'',
'        .my-dashboard-scope .w-24{color:#1f2937 }',
'        .my-dashboard-scope .w-full{color:#080707 }',
'        ',
'        .my-dashboard-scope .mt-6{margin-top:1.5rem}',
'        .my-dashboard-scope .mb-2{margin-bottom:0.5rem}',
'        .my-dashboard-scope .mb-3{margin-bottom:0.75rem}',
'        .my-dashboard-scope .mb-4{margin-bottom:1rem}',
'        .my-dashboard-scope .mb-6{margin-bottom:1.5rem}',
'        .my-dashboard-scope .p-2{padding:0.5rem}',
'        .my-dashboard-scope .p-3{padding:0.75rem}',
'        .my-dashboard-scope .p-4{padding:1rem}',
'        .my-dashboard-scope .px-2{padding-left:0.5rem;padding-right:0.5rem}',
'        .my-dashboard-scope .px-4{padding-left:1rem;padding-right:1rem}',
'        .my-dashboard-scope .px-6{padding-left:1.5rem;padding-right:1.5rem}',
'        .my-dashboard-scope .py-1{padding-top:0.25rem;padding-bottom:0.25rem}',
'        .my-dashboard-scope .py-2{padding-top:0.5rem;padding-bottom:0.5rem}',
'        .my-dashboard-scope .py-3{padding-top:0.75rem;padding-bottom:0.75rem}',
'        .my-dashboard-scope .py-4{padding-top:1rem;padding-bottom:1rem}',
'        .my-dashboard-scope .w-6{width:1.5rem}',
'        .my-dashboard-scope .w-24{width:6rem}',
'        .my-dashboard-scope .w-full{width:100%}',
'        .my-dashboard-scope .h-6{height:1.5rem}',
'        .my-dashboard-scope .h-full{height:100%}',
'        .my-dashboard-scope .min-h-screen{min-height:100vh}',
'        .my-dashboard-scope .text-xs{font-size:0.75rem;line-height:1rem}',
'        .my-dashboard-scope .text-sm{font-size:0.875rem;line-height:1.25rem}',
'        .my-dashboard-scope .text-lg{font-size:1.125rem;line-height:1.75rem}',
'        .my-dashboard-scope .text-xl{font-size:1.25rem;line-height:1.75rem}',
'        .my-dashboard-scope .text-2xl{font-size:1.5rem;line-height:2rem}',
'        .my-dashboard-scope .text-3xl{font-size:1.875rem;line-height:2.25rem}',
'        .my-dashboard-scope .font-medium{font-weight:500}',
'        .my-dashboard-scope .font-semibold{font-weight:600}',
'        .my-dashboard-scope .font-bold{font-weight:700}',
'        .my-dashboard-scope font-extrabold{font-weight:800}',
'        .my-dashboard-scope .uppercase{text-transform:uppercase}',
'        .my-dashboard-scope .truncate{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
'        .my-dashboard-scope .text-left{text-align:left}',
'        .my-dashboard-scope .text-center{text-align:center}',
'        .my-dashboard-scope .text-white{color:#fff}',
'        .my-dashboard-scope .text-gray-400{color:#9ca3af}',
'        .my-dashboard-scope .text-gray-500{color:#6b7280}',
'        .my-dashboard-scope .text-gray-700{color:#374151}',
'        .my-dashboard-scope .text-gray-800{color:#1f2937}',
'        .my-dashboard-scope .text-blue-600{color:#2563eb}',
'        .my-dashboard-scope .text-indigo-400{color:#818cf8}',
'        .my-dashboard-scope .text-yellow-500{color:#eab308}',
'        .my-dashboard-scope .bg-white{background-color:#fff}',
'        .my-dashboard-scope .bg-gray-50{background-color:#f9fafb}',
'        .my-dashboard-scope .bg-gray-100{background-color:#f3f4f6}',
'        .my-dashboard-scope .bg-gray-200{background-color:#e5e7eb}',
'        .my-dashboard-scope .bg-gray-800{background-color:#1f2937}',
'        .my-dashboard-scope .bg-blue-500{background-color:#3b82f6}',
'        .my-dashboard-scope .bg-green-500{background-color:#10b981}',
'        .my-dashboard-scope .bg-red-500{background-color:#ef4444}',
'        .my-dashboard-scope .bg-purple-500{background-color:#8b5cf6}',
'        .my-dashboard-scope .bg-indigo-500{background-color:#6366f1}',
'        .my-dashboard-scope .hover\\:bg-gray-100:hover{background-color:#f3f4f6}',
'        .my-dashboard-scope .hover\\:bg-gray-200:hover{background-color:#e5e7eb}',
'        .my-dashboard-scope .hover\\:bg-gray-300:hover{background-color:#d1d5db}',
'        .my-dashboard-scope .hover\\:bg-blue-600:hover{background-color:#2563eb}',
'       .my-dashboard-scope .hover\\:bg-green-600:hover{background-color:#059669}',
'        .my-dashboard-scope .hover\\:bg-red-600:hover{background-color:#dc2626}',
'        .my-dashboard-scope .hover\\:bg-purple-600:hover{background-color:#7c3aed}',
'        .my-dashboard-scope .hover\\:bg-gray-900:hover{background-color:#111827}',
'        .my-dashboard-scope .border{border-width:1px}',
'        .my-dashboard-scope .border-b{border-bottom-width:1px}',
'        .my-dashboard-scope .border-gray-200{border-color:#e5e7eb}',
'        .my-dashboard-scope .border-gray-300{border-color:#d1d5db}',
'        .my-dashboard-scope .rounded{border-radius:0.25rem}',
'        .my-dashboard-scope .rounded-lg{border-radius:0.5rem}',
'.my-dashboard-scope .rounded-xl{border-radius:0.75rem}',
'.my-dashboard-scope .rounded-full{border-radius:9999px}',
'.my-dashboard-scope .shadow-md{box-shadow:0 4px 6px -1px rgba(0,0,0,0.1),0 2px 4px -1px rgba(0,0,0,0.06)}',
'.my-dashboard-scope .shadow-xl{box-shadow:0 20px 25px -5px rgba(0,0,0,0.1),0 10px 10px -5px rgba(0,0,0,0.04)}',
'.my-dashboard-scope .transition{transition-property:background-color,border-color,color,fill,stroke,opacity,box-shadow,transform;transition-timing-function:cubic-bezier(0.4,0,0.2,1);transition-duration:150ms}',
'.my-dashboard-scope .duration-150{transition-duration:150ms}',
'.my-dashboard-scope .duration-300{transition-duration:300ms}',
'.my-dashboard-scope .transform{transform:var(--tw-transform)}',
'.my-dashboard-scope .hover\\:scale-105:hover{--tw-scale-x:1.05;--tw-scale-y:1.05;transform:scale(1.05)}',
'.my-dashboard-scope .opacity-0{opacity:0}',
'.my-dashboard-scope .opacity-40{opacity:0.4}',
'.my-dashboard-scope .overflow-auto{overflow:auto}',
'.my-dashboard-scope .overflow-hidden{overflow:hidden}',
'.my-dashboard-scope .flex-wrap{flex-wrap:wrap}',
'.my-dashboard-scope .items-center{align-items:center}',
'.my-dashboard-scope .items-end{align-items:flex-end}',
'.my-dashboard-scope .justify-between{justify-content:space-between}',
'.my-dashboard-scope .justify-end{justify-content:flex-end}',
'.my-dashboard-scope .justify-center{justify-content:center}',
'.my-dashboard-scope .flex-grow{flex-grow:1}',
'.my-dashboard-scope .gap-4{gap:1rem}',
'.my-dashboard-scope .space-x-3>:not([hidden])~:not([hidden]){margin-left:0.75rem}',
'        ',
'        /* Button Simulation Classes */',
'        .my-dashboard-scope .cursor-pointer{cursor:pointer}',
'        .my-dashboard-scope .select-none{-webkit-user-select:none;-moz-user-select:none;user-select:none}',
'        .my-dashboard-scope .inline-flex{display:inline-flex}',
'        ',
'        .my-dashboard-scope .focus\\:ring-blue-500:focus{box-shadow:0 0 0 3px rgba(59,130,246,0.5)}',
'        .my-dashboard-scope .focus\\:border-blue-500:focus{border-color:#3b82f6}',
'        .my-dashboard-scope .focus\\:outline-none:focus{outline:2px solid transparent}',
'',
'        /* Custom scrollbar */',
'        .my-dashboard-scope .custom-scrollbar::-webkit-scrollbar { width: 8px; height: 8px; }',
'        .my-dashboard-scope .custom-scrollbar::-webkit-scrollbar-thumb { background-color: var(--scrollbar-thumb); border-radius: 4px; }',
'        .my-dashboard-scope .custom-scrollbar::-webkit-scrollbar-track { background-color: var(--scrollbar-track); }',
'',
'        /* Theme variables */',
'        .my-dashboard-scope :root {',
'            --bg-color: #f7fafc; --text-color: #1a202c; --card-bg: #ffffff; --border-color: #e2e8f0;',
'            --accent-color: #4299e1; --scrollbar-thumb: #cbd5e0; --scrollbar-track: #f7fafc;',
'        }',
'        .my-dashboard-scope .dark-mode {',
'            --bg-color: #1a202c; --text-color: #e2e8f0; --card-bg: #2d3748; --border-color: #4a5568;',
'            --accent-color: #63b3ed; --scrollbar-thumb: #4a5568; --scrollbar-track: #2d3748;',
'        }',
'',
'        .my-dashboard-scope body { background-color: var(--bg-color); color: var(--text-color); transition: background-color 0.3s, color 0.3s; min-height: 100vh; font-family: ui-sans-serif, system-ui, sans-serif; overflow: auto; }',
'        ',
'        .my-dashboard-scope .table-card {',
'            background-color: var(--card-bg); border: 1px solid var(--border-color);',
'            transition: background-color 0.3s, border-color 0.3s;',
'            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);',
'            height: auto; min-height: 100px; flex: 0 0 auto;',
'        }',
'',
'        .my-dashboard-scope .table-cardsData {',
'            background-color: var(--card-bg); border: 1px solid var(--border-color);',
'            transition: background-color 0.3s, border-color 0.3s;',
'            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);',
'            max-height: 580px; min-height: 100px; flex: 0 0 auto;',
'        }',
'',
'        .my-dashboard-scope .drag-over { outline: 3px dashed var(--accent-color); background-color: rgba(99,179,237,0.1); }',
'        ',
'        /* Flex Layout */',
'        .my-dashboard-scope .main-container { width: 100%; min-width: 100%; }',
'        .my-dashboard-scope .dashboard-content { display: flex; flex-direction: column; gap: 1.5rem; padding: 1rem; width: max-content; min-width: 100%; }',
'        .my-dashboard-scope .dashboard-row { display: flex; flex-direction: row; gap: 1.5rem; width: 100%; }',
'        ',
'        .my-dashboard-scope .col-count-badge { position: absolute; top: 0.5rem; right: 0.5rem; background: rgba(66,153,225,0.9); color: white; border-radius: 0.25rem; padding: 0.125rem 0.5rem; font-size: 0.75rem; font-weight: 600; }',
'        ',
'        .my-dashboard-scope header { position: sticky; top: 0; left: 0; z-index: 40; background-color: var(--bg-color); padding: 1.5rem 0; width: 100vw; margin-left: calc(-50vw + 50%); border-bottom: 1px solid var(--border-color); }',
'        ',
'        .my-dashboard-scope .card-content { width: 100%; height: 100%; display: flex; flex-direction: column; }',
'        .my-dashboard-scope .preview-table { width: 100%; table-layout: auto; }',
'        .my-dashboard-scope .preview-table th, .preview-table td { white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
'         padding: 0.5rem; max-width: 200px; color: #e2e8f0;}',
'        .my-dashboard-scope .table-container { min-width: 0; overflow-x: auto; }',
'',
'        .my-dashboard-scope .preview-table tfoot th, .preview-table tfoot td {',
'     white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
'         padding: 0.5rem; max-width: 200px; color: #000000;',
'}',
'',
'',
'',
'        /* Dynamic Widths */',
'        .my-dashboard-scope .card-min { width: 300px; }',
'        .my-dashboard-scope .card-2-col { width: 350px; }',
'        .my-dashboard-scope .card-3-col { width: 400px; }',
'        .my-dashboard-scope .card-4-col { width: 500px; }',
'        .my-dashboard-scope .card-5-col { width: 600px; }',
'        .my-dashboard-scope .card-6-col { width: 700px; }',
'        .my-dashboard-scope .card-7-col { width: 800px; }',
'        .my-dashboard-scope .card-8-col { width: 900px; }',
'        .my-dashboard-scope .card-large { width: 2000px; }',
'',
'        /* Modal - INCREASED Z-INDEX FOR APEX */',
'        .my-dashboard-scope .modal-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(0,0,0,0.5); z-index: 9999; display: none; align-items: center; justify-content: center; padding: 1rem; }',
'        .my-dashboard-scope .modal-overlay.active { display: flex; }',
'        .my-dashboard-scope .modal-content { background-color: var(--card-bg); border-radius: 0.75rem; padding: 1.5rem; width: 100%; max-width: 56rem; max-height: 90vh; overflow-y: auto; position: relative; }',
'',
'        /* Dark mode helpers */',
'        .my-dashboard-scope .dark-mode .dark\\:bg-gray-700 { background-color: #374151; }',
'        .my-dashboard-scope .dark-mode .dark\\:text-gray-100 { color: #f3f4f6; }',
'        .my-dashboard-scope .dark-mode .dark\\:text-gray-300 { color: #d1d5db; }',
'        .my-dashboard-scope .dark-mode .dark\\:border-gray-600 { border-color: #4b5563; }',
'',
'',
'',
' ',
'',
'',
' .my-dashboard-scope .preview-table {',
'    position: relative;',
'}',
'',
'.my-dashboard-scope .preview-table thead th {',
'    position: sticky;',
'    top: 0;',
'    background: inherit;',
'}',
'',
'.my-dashboard-scope .preview-table tfoot td {',
'    position: sticky;',
'    bottom: 0;',
'    background: inherit;',
'}',
' ',
'',
'',
' ',
'',
'',
'',
' /* Table text colors for light and dark mode */',
'.my-dashboard-scope .preview-table {',
'    color: var(--text-color);',
'}',
'',
'.my-dashboard-scope .preview-table th,',
'.my-dashboard-scope .preview-table td {',
'    color: inherit;',
'}',
'',
'.my-dashboard-scope .preview-table thead th {',
'    color: var(--text-color);',
'}',
'',
'.my-dashboard-scope .preview-table tbody td {',
'    color: var(--text-color);',
'}',
'',
' ',
'',
'',
'',
'/* Conditional formatting should still work in dark mode */',
'html.dark .my-dashboard-scope .preview-table tbody td[style*="color:"] {',
'    /* Keep the conditional formatting colors but ensure they''re visible */',
'    opacity: 0.9;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'17'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(27224043200332280)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(8558440305922134)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(27225096151348101)
,p_plug_name=>'New'
,p_region_css_classes=>'my-dashboard-scope'
,p_region_template_options=>'#DEFAULT#:t-Region--noPadding:t-Region--removeHeader js-removeLandmark:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>50
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div id="saveGlobalLayoutBtn" role="button" class="cursor-pointer select-none inline-flex bg-gray-800 dark:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-gray-900 dark:hover:bg-gray-500 transition duration-150 shadow-md items-center">',
'                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-'
||'3 3m0 0l-3-3m3 3V4"></path></svg>',
'                        Save Layout',
'                    </div>',
'                    <div id="themeToggle" role="button" class="cursor-pointer select-none inline-flex p-2 rounded-full bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors duration-300 shadow-md">',
'                        <svg id="sunIcon" class="w-6 h-6 text-yellow-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.'
||'707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"></path></svg>',
'                        <svg id="moonIcon" class="w-6 h-6 text-indigo-400 hidden" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 '
||'9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"></path></svg>',
'                    </div>',
'<div id="toggleEmptyCardsBtn" role="button" class="cursor-pointer select-none inline-flex bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded-lg hover:bg-gray-300 transition duration-150 shadow-md items-center justify-center">',
'    Admin User',
'</div>',
'',
'<div id="refreshBtn" role="button" class="cursor-pointer select-none inline-flex bg-gray-200 text-gray-800 font-semibold py-2 px-4 rounded-lg hover:bg-gray-300 transition duration-150 shadow-md items-center justify-center">',
'    Refresh Summary',
'</div>',
'',
'     <div class="mt-4 p-4 table-card rounded-lg adminheader">',
'                <div class="flex flex-wrap gap-4 items-end">',
'                    <div>',
'                        <label class="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">Rows:</label>',
'                        <input type="number" id="inputRows" value="2" min="1" max="20" class="w-24 p-2 border rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-100">',
'                    </div>',
'                    <div>',
'                        <label class="block text-sm font-medium mb-1 text-gray-700 dark:text-gray-300">Columns:</label>',
'                        <input type="number" id="inputCols" value="7" min="1" max="20" class="w-24 p-2 border rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-100">',
'                    </div>',
'                    ',
'                    <div id="updateGridBtn" role="button" class="cursor-pointer select-none inline-flex bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-600 transition duration-150 shadow-md items-center justify-center">Update '
||'Grid</div>',
'                    ',
'                    <div class="w-px h-10 bg-gray-300 mx-2"></div>',
'                    ',
'                    <div id="addSampleData" role="button" class="cursor-pointer select-none inline-flex bg-green-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-green-600 transition duration-150 shadow-md items-center justify-center">Add S'
||'ample</div>',
'                    <div id="fillAllCells" role="button" class="cursor-pointer select-none inline-flex bg-purple-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-purple-600 transition duration-150 shadow-md items-center justify-center">Fill'
||' All</div>',
'                </div>',
'            </div>',
'                            ',
'<div class="my-dashboard-scope">',
'<body class="custom-scrollbar">',
'    <div class="main-container">',
'        <!-- <header class="px-6">',
'            <div class="flex justify-between items-center">',
'                 ',
'                <div class="flex items-center gap-4">',
'                    ',
'                    ',
'                </div>',
'            </div>',
'',
'           ',
'        </header> -->',
'',
'        <div class="custom-scrollbar">',
'            <main id="mainGrid" class="dashboard-content"></main>',
'        </div>',
'    </div>',
'',
'    <div id="dataModal" class="modal-overlay">',
'        <div class="modal-content">',
'            <h2 class="text-2xl font-bold mb-4 dark:text-gray-100">Edit Table Data',
'            <div id="closeModalBtn" role="button" class="cursor-pointer select-none absolute top-4 right-4 p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 dark:text-gray-300">',
'                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>',
'            </div>',
'            </h2>',
'            <div class="mb-4">',
'                <label for="tableNameInput" class="block text-sm font-medium mb-1 dark:text-gray-300">Table Title:</label>',
'                <input type="text" id="tableNameInput" class="w-full p-2 border rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-100 focus:ring-blue-500 focus:border-blue-500" placeholder="Enter table name...">',
'            </div>',
'            <!-- <div class="mb-4">',
'                <label for="tableNameInput" class="block text-sm font-medium mb-1 dark:text-gray-300">Report:</label>',
'                <input type="text" id="tableNameInput" class="w-full p-2 border rounded bg-gray-50 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-100 focus:ring-blue-500 focus:border-blue-500" placeholder="Enter table name...">',
'            </div> -->',
'            <div class="mb-4">',
'                <label for="reportSelect" class="block text-sm font-medium text-gray-300 mb-1">Select Existing Report</label>',
'                <select ',
'                    id="reportSelect" ',
'                    class="w-full bg-gray-700 border border-gray-600 rounded-md p-2 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"',
'                    disabled >',
'                    <option value="">-- Select Hotel First --</option>',
'                </select>',
'            </div>',
'            <div id="jsonInputSection" class="mb-6">',
'                <label for="jsonInput" class="block text-sm font-medium mb-2 dark:text-gray-300"></label>',
'                <textarea id="jsonInput" rows="6" class="w-full p-3 rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 dark:text-gray-100 focus:ring-blue-500 focus:border-blue-500" placeholder=''[{"id": 1, "name": "Item'
||' A"}]''></textarea>',
'                <div id="processJsonBtn" role="button" class="cursor-pointer select-none mt-3 inline-flex bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-600 transition duration-150 shadow-md items-center justify-center">Load '
||'Table</div>',
'            </div>',
'            <div id="dynamicTableContainer" class="hidden mt-6">',
'                <h3 class="text-xl font-semibold mb-3 dark:text-gray-100"></h3>',
'                <div class="inner-table-container max-h-96 overflow-y-auto overflow-x-auto custom-scrollbar rounded-lg border border-gray-200 dark:border-gray-600">',
'',
'                      ',
'                </div>',
'                <div class="flex justify-end space-x-3 mt-6">',
'                    <div id="deleteTableBtn" role="button" class="cursor-pointer select-none inline-flex bg-red-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-red-600 transition duration-150 shadow-md items-center justify-center">Delete T'
||'able</div>',
'                    <div id="saveTableBtn" role="button" class="cursor-pointer select-none inline-flex bg-green-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-green-600 transition duration-150 shadow-md items-center justify-center">Save T'
||'able</div>',
'                </div>',
'            </div>',
'        </div>',
'    </div>',
'',
'    <div id="messageBox" class="hidden fixed bottom-4 right-4 p-3 rounded-lg shadow-xl text-white font-medium" role="alert"></div>',
'</body>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(28720566178061101)
,p_name=>'P167_USER'
,p_item_sequence=>40
,p_item_default=>'&APP_USER.'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp.component_end;
end;
/
