BEGIN
  APEX_JSON.OPEN_ARRAY;
  IF apex_application.g_x01 = 'HOTEL' THEN
      FOR rec IN (SELECT ID, HOTEL_NAME FROM UR_HOTELS order by upper(hotel_name)) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('ID', rec.ID);
        APEX_JSON.WRITE('HOTEL_NAME', rec.HOTEL_NAME);
        APEX_JSON.CLOSE_OBJECT;
      END LOOP;
  ELSIF  apex_application.g_x01 = 'REPORT_DETAIL' THEN
     FOR rec IN (SELECT ID, NAME, DEFINITION,DEFINITION_JSON,DB_OBJECT_NAME, COLUMN_ALIAS,EXPRESSIONS_CLOB FROM TEMP_UR_REPORTS 
    WHERE ID = apex_application.g_x02
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('ID', rec.ID);
        APEX_JSON.WRITE('REPORT_NAME', rec.NAME);
        APEX_JSON.WRITE('DEFINITION', rec.DEFINITION);
        APEX_JSON.WRITE('DB_OBJECT_NAME', rec.DB_OBJECT_NAME);
        APEX_JSON.WRITE('DEFINITION_JSON', rec.DEFINITION_JSON);
        APEX_JSON.WRITE('COLUMN_ALIAS', rec.COLUMN_ALIAS);
        APEX_JSON.WRITE('EXPRESSIONS_CLOB', rec.EXPRESSIONS_CLOB);
        APEX_JSON.CLOSE_OBJECT;
        END LOOP;
  ELSE
    FOR rec IN (SELECT ID, NAME, DEFINITION FROM TEMP_UR_REPORTS 
    WHERE HOTEL_ID = apex_application.g_x02
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('ID', rec.ID);
        APEX_JSON.WRITE('REPORT_NAME', rec.NAME);
        APEX_JSON.WRITE('DEFINITION', rec.DEFINITION); 
        APEX_JSON.CLOSE_OBJECT;
        END LOOP;
  END IF;
  APEX_JSON.CLOSE_ARRAY;
END;