prompt --application/shared_components/logic/application_processes/ajx_get_report_data
begin
--   Manifest
--     APPLICATION PROCESS: AJX_GET_REPORT_DATA
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>7945143549875994
,p_default_application_id=>103
,p_default_id_offset=>0
,p_default_owner=>'WKSP_DEV'
);
wwv_flow_imp_shared.create_flow_process(
 p_id=>wwv_flow_imp.id(13515514348470830)
,p_process_sequence=>1
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'AJX_GET_REPORT_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    l_columns   APEX_JSON.t_values;',
'    l_aliases   APEX_JSON.t_values;',
'    l_sql       VARCHAR2(32767);',
'    l_cursor    INTEGER;',
'    l_desc      DBMS_SQL.DESC_TAB2;',
'    l_col_cnt   INTEGER;',
'    l_val_vc    VARCHAR2(4000);',
'    l_col_name  VARCHAR2(4000);',
'    l_dummy     INTEGER;',
'    l_name      VARCHAR2(4000);',
'    l_alias     VARCHAR2(4000);',
'BEGIN',
'',
'IF apex_application.g_x01 = ''TEMPLATE_REPORT_DATA'' THEN',
'',
'APEX_JSON.parse(l_columns, apex_application.g_x02);',
'',
'    -- Build SELECT list',
'    l_sql := ''SELECT '';',
'    FOR i IN 1 .. APEX_JSON.get_count(p_path => ''.'', p_values => l_columns) LOOP',
'        IF i > 1 THEN',
'            l_sql := l_sql || '', '';',
'        END IF;',
'        l_sql := l_sql || ''"'' || APEX_JSON.get_varchar2(p_path => ''[''||i||''].name'', p_values => l_columns) || ''"'';',
'    END LOOP;',
'    --l_sql := l_sql || '' FROM ''||apex_application.g_x03||'' where rownum <= 10'';',
'    l_sql := l_sql||'' ,PK_COL '' || '' FROM ''||apex_application.g_x03||'' FETCH FIRST 10 ROWS ONLY'';',
'  --  l_sql := l_sql || '' FROM ''||apex_application.g_x03||'''';',
'',
'    -- Prepare and describe',
'    l_cursor := DBMS_SQL.open_cursor;',
'    DBMS_SQL.parse(l_cursor, l_sql, DBMS_SQL.native);',
'    DBMS_SQL.describe_columns2(l_cursor, l_col_cnt, l_desc);',
'',
'    -- Define all columns as varchar2',
'    FOR i IN 1 .. l_col_cnt LOOP',
'        DBMS_SQL.define_column(l_cursor, i, l_val_vc, 4000);',
'    END LOOP;',
'',
'    ',
'    l_dummy := DBMS_SQL.execute(l_cursor);',
'',
'    -- Output JSON',
'    APEX_JSON.open_object;',
'    APEX_JSON.open_array(''rows'');',
'',
'    WHILE DBMS_SQL.fetch_rows(l_cursor) > 0 LOOP',
'        APEX_JSON.open_object;',
'        FOR i IN 1 .. l_col_cnt LOOP',
'            l_col_name := l_desc(i).col_name;',
'            DBMS_SQL.column_value(l_cursor, i, l_val_vc);',
'             IF l_val_vc IS NULL THEN',
'             --   DBMS_OUTPUT.put_line(l_col_name || '' = NULL'');',
'                APEX_JSON.write(l_col_name,  '' '');',
'            ELSE',
'               -- DBMS_OUTPUT.put_line(l_col_name || '' = '' || l_val_vc);',
'                APEX_JSON.write(l_col_name, l_val_vc);',
'            END IF;',
'            ',
'        END LOOP;',
'        APEX_JSON.close_object;',
'    END LOOP;',
'',
'    APEX_JSON.close_array;',
'    APEX_JSON.close_object;',
'',
'    DBMS_SQL.close_cursor(l_cursor);',
'',
'ELSE',
'    -- Parse incoming JSON',
'    APEX_JSON.parse(l_columns, apex_application.g_x01); -- columns_list',
'    APEX_JSON.parse(l_aliases, apex_application.g_x02); -- col_alias',
'',
'    -- Build SELECT list',
'    l_sql := ''SELECT '';',
'    FOR i IN 1 .. APEX_JSON.get_count(p_path => ''.'', p_values => l_columns) LOOP',
'        IF i > 1 THEN',
'            l_sql := l_sql || '', '';',
'        END IF;',
'',
'        -- column name (e.g. BOOKING_ID - VK Sample Hotel Data)',
'        l_name := APEX_JSON.get_varchar2(p_path => ''[''||i||''].name'', p_values => l_columns);',
'',
'        -- find matching alias_name from col_alias',
'        SELECT MAX(alias_name)',
'        INTO l_alias',
'        FROM JSON_TABLE(apex_application.g_x02, ''$.selectedColumns[*]''',
'              COLUMNS (',
'                col_name   VARCHAR2(200) PATH ''$.col_name'',',
'                temp_name  VARCHAR2(200) PATH ''$.temp_name'',',
'                alias_name VARCHAR2(200) PATH ''$.alias_name''',
'              ))',
'        WHERE col_name || '' - '' || temp_name = l_name;',
'',
'        -- fallback if no alias found',
'        IF l_alias IS NULL THEN',
'            l_alias := l_name;',
'        END IF;',
'',
'        -- add to SQL',
'       -- l_sql := l_sql || ''"'' || l_name || ''" AS "'' || l_alias || ''"'';',
'		l_sql := l_sql || ''"'' || l_name || ''"'' || '' AS "'' || REPLACE(l_alias,''"'') || ''"'';',
'',
'    END LOOP;',
'',
'    l_sql := l_sql || '' FROM ''||apex_application.g_x03;  -- pass db object name separately',
'	',
'',
'    -- Prepare, describe, execute',
'    l_cursor := DBMS_SQL.open_cursor;',
'    DBMS_SQL.parse(l_cursor, l_sql, DBMS_SQL.native);',
'    DBMS_SQL.describe_columns2(l_cursor, l_col_cnt, l_desc);',
'',
'    FOR i IN 1 .. l_col_cnt LOOP',
'        DBMS_SQL.define_column(l_cursor, i, l_val_vc, 4000);',
'    END LOOP;',
'',
'    l_dummy := DBMS_SQL.execute(l_cursor);',
'',
'    -- Output JSON',
'    APEX_JSON.open_object;',
'    APEX_JSON.open_array(''rows'');',
'',
'    WHILE DBMS_SQL.fetch_rows(l_cursor) > 0 LOOP',
'        APEX_JSON.open_object;',
'        FOR i IN 1 .. l_col_cnt LOOP',
'            l_col_name := l_desc(i).col_name;',
'            DBMS_SQL.column_value(l_cursor, i, l_val_vc);',
'            APEX_JSON.write(l_col_name, l_val_vc);',
'        END LOOP;',
'        APEX_JSON.close_object;',
'    END LOOP;',
'',
'    APEX_JSON.close_array;',
'    APEX_JSON.close_object;',
'',
'    DBMS_SQL.close_cursor(l_cursor);',
'    END IF;',
'EXCEPTION',
'    WHEN OTHERS THEN',
'        IF DBMS_SQL.is_open(l_cursor) THEN',
'            DBMS_SQL.close_cursor(l_cursor);',
'        END IF;',
'        RAISE;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_security_scheme=>'MUST_NOT_BE_PUBLIC_USER'
,p_version_scn=>45852316681280
);
wwv_flow_imp.component_end;
end;
/
