prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/app_103_push_notifications_credentials_2.sql
@@workspace/credentials/credentials_for_openai.sql
@@workspace/remote_servers/api_openai_com_v1.sql
@@application/shared_components/data_profiles/openai.sql
@@application/shared_components/web_sources/openai.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/sample_load_data_template_xlsx.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/interactive_report_css.sql
@@application/shared_components/files/interactive_report_min_css.sql
@@application/shared_components/files/model_page_css.sql
@@application/shared_components/files/model_page_min_css.sql
@@application/shared_components/files/dynamictbl_js.sql
@@application/shared_components/files/dynamictbl_min_js.sql
@@application/shared_components/files/dynamiccss_css.sql
@@application/shared_components/files/dynamiccss_min_css.sql
@@application/shared_components/files/dynamicreportjs_min_js.sql
@@application/shared_components/files/reportdashboardjs_min_js.sql
@@application/shared_components/files/gridreportsummary_min_js.sql
@@application/shared_components/files/360_3608307_placeholder_hotel_house_png.sql
@@application/shared_components/files/algopgjs_min_js.sql
@@application/shared_components/files/showalert_js.sql
@@application/shared_components/files/dynamicreportjs_js.sql
@@application/shared_components/files/hotel_jpeg.sql
@@application/shared_components/files/reportdashboardjs_js.sql
@@application/shared_components/files/algopgjs_js.sql
@@application/shared_components/files/showalert_min_js.sql
@@application/shared_components/files/reportsummary_js.sql
@@application/shared_components/files/reportsummary_min_js.sql
@@application/shared_components/files/icons_untapped_revenue_branding_2_sq_logo_png.sql
@@application/shared_components/files/gridreportsummary_js.sql
@@application/shared_components/files/sample_events_txt.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/save_card_field.sql
@@application/shared_components/logic/application_processes/get_blob.sql
@@application/shared_components/logic/application_processes/ajx_get_report_hotel.sql
@@application/shared_components/logic/application_processes/ajx_get_hotel_templates.sql
@@application/shared_components/logic/application_processes/ajx_get_hotel_temp_all.sql
@@application/shared_components/logic/application_processes/ajx_manage_report_view.sql
@@application/shared_components/logic/application_processes/ajx_get_temp_col_details.sql
@@application/shared_components/logic/application_processes/ajx_get_report_data.sql
@@application/shared_components/logic/application_processes/ajx_manage_report_dashboard.sql
@@application/shared_components/logic/application_processes/ajx_manage_algo.sql
@@application/shared_components/logic/application_processes/ajx_get_report_all_qualifiers.sql
@@application/shared_components/logic/application_processes/download_file.sql
@@application/shared_components/logic/application_processes/ajx_get_usr_type.sql
@@application/shared_components/logic/application_items/g_hotel_id.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/ur_algo_conditions_operators.sql
@@application/shared_components/user_interface/lovs/ur_attribute_qualifiers.sql
@@application/shared_components/user_interface/lovs/ur_bed_types.sql
@@application/shared_components/user_interface/lovs/ur_booking_days.sql
@@application/shared_components/user_interface/lovs/ur_cancellation_reason.sql
@@application/shared_components/user_interface/lovs/ur_contact_types.sql
@@application/shared_components/user_interface/lovs/ur_event_score.sql
@@application/shared_components/user_interface/lovs/ur_event_types.sql
@@application/shared_components/user_interface/lovs/ur_expression_functions.sql
@@application/shared_components/user_interface/lovs/ur_expression_operators.sql
@@application/shared_components/user_interface/lovs/ur_hotel_price_override_reason.sql
@@application/shared_components/user_interface/lovs/ur_hotel_price_override_type.sql
@@application/shared_components/user_interface/lovs/ur_lead_time_types.sql
@@application/shared_components/user_interface/lovs/ur_mapping_types.sql
@@application/shared_components/user_interface/lovs/ur_property_ranking.sql
@@application/shared_components/user_interface/lovs/ur_reservation_types.sql
@@application/shared_components/user_interface/lovs/ur_reservstion_exception_type.sql
@@application/shared_components/user_interface/lovs/ur_room_suppliment_types.sql
@@application/shared_components/user_interface/lovs/ur_template_types.sql
@@application/shared_components/user_interface/lovs/ur_user_status.sql
@@application/shared_components/user_interface/lovs/ur_user_type.sql
@@application/shared_components/user_interface/lovs/ur_hotels_hotel_name.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/data_loads/ur_data_load.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00004.sql
@@application/pages/page_00007.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00017.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00029.sql
@@application/pages/page_00167.sql
@@application/pages/page_01001.sql
@@application/pages/page_01002.sql
@@application/pages/page_01006.sql
@@application/pages/page_01010.sql
@@application/pages/page_01011.sql
@@application/pages/page_01020.sql
@@application/pages/page_01023.sql
@@application/pages/page_01026.sql
@@application/pages/page_01027.sql
@@application/pages/page_01033.sql
@@application/pages/page_01034.sql
@@application/pages/page_01050.sql
@@application/pages/page_01071.sql
@@application/pages/page_01075.sql
@@application/pages/page_01601.sql
@@application/pages/page_01611.sql
@@application/pages/page_01612.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10035.sql
@@application/pages/page_10036.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10055.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/pages/page_20000.sql
@@application/pages/page_20010.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_installation_script_251223.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
