  CREATE TABLE "DEBUG_LOG" 
   (	"ID" RAW(16) DEFAULT sys_guid(), 
	"LOG_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"MESSAGE" CLOB, 
	"FULL_SQL" CLOB
   ) ;

  CREATE TABLE "TEMP_BLOB" 
   (	"ID" NUMBER(22,0) NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER(22,0), 
	"NAME" VARCHAR2(400), 
	"FILENAME" VARCHAR2(400), 
	"MIME_TYPE" VARCHAR2(255), 
	"CREATED_ON" DATE, 
	"BLOB_CONTENT" BLOB, 
	"PROFILE" CLOB, 
	"RECORDS" NUMBER, 
	"COLUMNS" CLOB, 
	 CONSTRAINT "PK_TEMP_BLOB" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TEMP_UR_REPORTS" 
   (	"ID" VARCHAR2(22210) DEFAULT sys_guid() NOT NULL ENABLE, 
	"HOTEL_ID" VARCHAR2(106), 
	"KEY" VARCHAR2(110) DEFAULT sys_guid(), 
	"NAME" VARCHAR2(100), 
	"TYPE" VARCHAR2(50), 
	"ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"DEFINITION" CLOB, 
	"DB_OBJECT_NAME" VARCHAR2(150), 
	"DB_OBJECT_CREATED_ON" DATE, 
	"ROWS_COUNT" NUMBER, 
	"TABLE_SPACE_SIZE" NUMBER, 
	"CREATED_BY" RAW(16), 
	"UPDATED_BY" RAW(16), 
	"CREATED_ON" DATE, 
	"UPDATED_ON" DATE, 
	"DEFINITION_JSON" CLOB, 
	"COLUMN_ALIAS" CLOB, 
	"EXPRESSIONS_CLOB" CLOB
   ) ;

  CREATE TABLE "TEMP_UR_REPORT_DASHBOARDS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"KEY" VARCHAR2(110), 
	"NAME" VARCHAR2(100), 
	"TYPE" VARCHAR2(50), 
	"ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"DEFINITION" CLOB, 
	"SUMMARY" CLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_HOTELS" 
   (	"ID" RAW(16) NOT NULL ENABLE, 
	"GROUP_ID" RAW(16), 
	"HOTEL_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STAR_RATING" NUMBER(1,0), 
	"ADDRESS_ID" RAW(16), 
	"CONTACT_ID" RAW(16), 
	"OPENING_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(3) DEFAULT 'GBP', 
	"ASSOCIATION_START_DATE" DATE, 
	"ASSOCIATION_END_DATE" DATE, 
	"ASSOCIATED_USER_ID" RAW(16), 
	"ALGORITHM_ID" RAW(16), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	"IMAGE_NAME" VARCHAR2(40 CHAR), 
	"IMG_TYPE" VARCHAR2(100 CHAR), 
	"OCCUPANCY" NUMBER, 
	 CONSTRAINT "PK_UR_HOTELS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_INTERFACE_LOGS" 
   (	"ID" RAW(16) NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"TEMPLATE_ID" RAW(16) NOT NULL ENABLE, 
	"INTERFACE_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"LOAD_START_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"LOAD_END_TIME" TIMESTAMP (6), 
	"LOAD_MAPPING" CLOB, 
	"LOAD_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"RECORDS_PROCESSED" NUMBER, 
	"RECORDS_SUCCESSFUL" NUMBER, 
	"RECORDS_FAILED" NUMBER, 
	"ERROR_DETAILS" VARCHAR2(1000), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"FILE_ID" NUMBER, 
	"ERROR_JSON" CLOB, 
	 CHECK (Records_Processed >= 0) ENABLE, 
	 CHECK (Records_Successful >= 0) ENABLE, 
	 CHECK (Records_Failed >= 0) ENABLE, 
	 CONSTRAINT "PK_UR_INTERFACE_LOGS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UR_INTERFACE_LOGS_CON" UNIQUE ("FILE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_REPORTS" 
   (	"ID" RAW(16) DEFAULT sys_guid() NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"KEY" VARCHAR2(110) DEFAULT sys_guid(), 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50), 
	"ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DEFINITION" CLOB NOT NULL ENABLE, 
	"DB_OBJECT_NAME" VARCHAR2(150), 
	"DB_OBJECT_CREATED_ON" DATE NOT NULL ENABLE, 
	"ROWS_COUNT" NUMBER, 
	"TABLE_SPACE_SIZE" NUMBER, 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	 CHECK (Active IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_UR_REPORTS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_REPORTS_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_REPORT_DASHBOARDS" 
   (	"ID" RAW(16) NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"KEY" VARCHAR2(110) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50), 
	"ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"DEFINITION" CLOB NOT NULL ENABLE, 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	 CHECK (ACTIVE IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CK_KEY_FORMAT" CHECK (
    REGEXP_LIKE("KEY", '^[A-Z0-9_]+$')
  ) ENABLE, 
	 CONSTRAINT "PK_UR_REPORT_DASHBOARDS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_REPORT_DASHBOARDS_HOTEL_ID" UNIQUE ("HOTEL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_REPORT_DASHBOARDS_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_REPORT_DASHBOARDS_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_TEMPLATES" 
   (	"ID" RAW(32) DEFAULT sys_guid() NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"KEY" VARCHAR2(110) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DEFINITION" CLOB NOT NULL ENABLE, 
	"DB_OBJECT_NAME" VARCHAR2(150), 
	"DB_OBJECT_CREATED_ON" DATE, 
	"ROWS_COUNT" NUMBER, 
	"TABLE_SPACE_SIZE" NUMBER, 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"DB_VIEW_OBJECT_NAME" VARCHAR2(150), 
	"DB_VIEW_OBJECT_CREATED_ON" DATE, 
	 CHECK (Active IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_UR_TEMPLATES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_TEMPLATES_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "XXPEL_WF_GLOBAL_PROFILES_TBL" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"KEY" VARCHAR2(2000 CHAR), 
	"NAME" VARCHAR2(2000 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"VALUE" VARCHAR2(2000 CHAR), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" VARCHAR2(2000 CHAR), 
	"UPDATED_BY" VARCHAR2(2000 CHAR), 
	"CREATED_ON" DATE, 
	"UPDATED_ON" DATE, 
	"ATTRIBUTE1" VARCHAR2(2000 CHAR), 
	"ATTRIBUTE2" VARCHAR2(2000 CHAR), 
	"ATTRIBUTE3" VARCHAR2(2000 CHAR), 
	"ATTRIBUTE4" VARCHAR2(2000 CHAR), 
	"ATTRIBUTE5" VARCHAR2(2000 CHAR), 
	 CONSTRAINT "XXPEL_WF_GLOBAL_PROFILES_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "KEY_UNIQUE" UNIQUE ("KEY")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_HOTEL_ACCESSES" 
   (	"HOTEL_ID" RAW(16) NOT NULL ENABLE, 
	"USER_ID" RAW(16) NOT NULL ENABLE, 
	"ACCESS_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_UR_HOTEL_ACCESSES" PRIMARY KEY ("HOTEL_ID", "USER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_HOTEL_GROUPS" 
   (	"ID" RAW(16), 
	"GROUP_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250), 
	"ADDRESS_ID" RAW(16), 
	"CONTACT_ID" RAW(16), 
	"ASSOCIATION_START_DATE" DATE, 
	"ASSOCIATION_END_DATE" DATE, 
	"ASSOCIATED_EMP_ID" RAW(16), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_UR_HOTEL_GROUPS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_HOTEL_GROUPS_NAME" UNIQUE ("GROUP_NAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_HOTEL_PRICE_OVERRIDE" 
   (	"ID" RAW(16) NOT NULL ENABLE, 
	"STAY_DATE" DATE NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(10) DEFAULT 'Retail' NOT NULL ENABLE, 
	"PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"REASON" VARCHAR2(120), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) DEFAULT 'A' NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(150), 
	 CONSTRAINT "UR_HPRICOVR_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UR_HPRICOVR_PRICE_CHK" CHECK (Price > 0) ENABLE
   ) ;

  CREATE TABLE "UR_HOTEL_RESERVATIONS" 
   (	"ID" RAW(16), 
	"RES_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16), 
	"ARRIVAL_DATE" DATE NOT NULL ENABLE, 
	"NUMBER_OF_NIGHTS" NUMBER(3,0) NOT NULL ENABLE, 
	"ROOMS_BOOKED" NUMBER(5,0) NOT NULL ENABLE, 
	"TOTAL_BOOKING_VALUE" NUMBER(12,2) NOT NULL ENABLE, 
	"CHARGED_FLAG" CHAR(1), 
	"EXCEPTION_AMOUNT" NUMBER(12,2) NOT NULL ENABLE, 
	"APPROVED_BY" VARCHAR2(100), 
	"NOTES" VARCHAR2(1000), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"ATTRIBUTE1" VARCHAR2(100), 
	"ATTRIBUTE2" VARCHAR2(100), 
	"ATTRIBUTE3" VARCHAR2(100), 
	"ATTRIBUTE4" VARCHAR2(100), 
	"ATTRIBUTE5" VARCHAR2(100), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" DATE, 
	"ATTRIBUTE10" DATE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"RESERVATION_TYPE" VARCHAR2(2), 
	"EXCEPTION_DATE" DATE, 
	"EXCEPTION_REASON" VARCHAR2(250), 
	"RESERVATION_EXCEPTION_TYPE" VARCHAR2(50), 
	"APPROVED_BY_MANUAL" VARCHAR2(100), 
	"ROOM_TYPE_ID" RAW(16), 
	 CHECK (Number_of_Nights > 0) ENABLE, 
	 CHECK (Rooms_Booked >= 0) ENABLE, 
	 CHECK (Total_Booking_Value >= 0) ENABLE, 
	 CHECK (Charged_Flag IN ('Y', 'N')) ENABLE, 
	 CHECK ("EXCEPTION_AMOUNT">=0) ENABLE, 
	 CONSTRAINT "PK_UR_HOTEL_RESERVATIONS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_HOTEL_RES_UNIQUE_NUMBER" UNIQUE ("HOTEL_ID", "RES_NUMBER")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_HOTEL_ROOM_TYPES" 
   (	"ROOM_TYPE_ID" RAW(16) NOT NULL ENABLE, 
	"HOTEL_ID" RAW(16) NOT NULL ENABLE, 
	"ROOM_TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"MAX_OCCUPANCY" NUMBER(2,0) NOT NULL ENABLE, 
	"BED_TYPE" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(250), 
	"CREATED_BY" RAW(16) NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) NOT NULL ENABLE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE NOT NULL ENABLE, 
	"PRICE" NUMBER, 
	"SUPPLIMENT_TYPE" VARCHAR2(3), 
	"SUPPLIEMENT_PRICE_MIN" NUMBER, 
	"SUPPLIMENT_PRICE_MAX" NUMBER, 
	 CONSTRAINT "PK_UR_HOTEL_ROOM_TYPES" PRIMARY KEY ("ROOM_TYPE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_PROFILE_OPTIONS" 
   (	"ID" RAW(16) NOT NULL ENABLE, 
	"KEY" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"VALUE" VARCHAR2(500) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" RAW(16), 
	"UPDATED_BY" RAW(16), 
	"CREATED_ON" DATE, 
	"UPDATED_ON" DATE, 
	 CONSTRAINT "PK_UR_PROFILE_OPTIONS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_PROFILE_OPTIONS_KEY" UNIQUE ("KEY")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UR_USERS" 
   (	"USER_ID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150) NOT NULL ENABLE, 
	"CONTACT_NUMBER" NUMBER, 
	"USER_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"LOGIN_METHOD" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(256), 
	"CREATED_BY" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"UPDATED_BY" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_ON" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(255), 
	"NOTES" VARCHAR2(50), 
	 CONSTRAINT "PK_UR_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_UR_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "XX_FEEDBACK_EMAIL_DETAILS" 
   (	"EMAIL_DETAILS" VARCHAR2(2000)
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTELS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTELS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

        IF :NEW.CURRENCY_CODE IS NULL THEN
            :NEW.CURRENCY_CODE := 'GBP';
        END IF;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTELS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_GROUPS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_GROUPS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_GROUPS_BI_TRG" ENABLE;

   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."ID" IS 'UUID - Unique attribute identifier (Primary Key).';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."STAY_DATE" IS 'The specific date for which the price is overridden.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."HOTEL_ID" IS 'Optional Foreign Key to a Hotel table to limit the override to a specific hotel.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."TYPE" IS 'Pricing Type (e.g., Retail, Group).';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."PRICE" IS 'The overridden price for the stay date.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."REASON" IS 'Justification for the price override.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."CREATED_BY" IS 'UUID of the user who created the record.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."UPDATED_BY" IS 'UUID of the user who last updated the record.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."CREATED_ON" IS 'Timestamp of when the record was created.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."UPDATED_ON" IS 'Timestamp of when the record was last updated.';
   COMMENT ON TABLE "UR_HOTEL_PRICE_OVERRIDE"  IS 'Stores daily price overrides for hotels.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_PRICE_OVERRIDE_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_PRICE_OVERRIDE
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
BEGIN
  -- Assign GUID if missing
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch user_id from UR_USERS using APEX user
  SELECT USER_ID 
    INTO v_user_id 
    FROM UR_USERS
   WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  ---------------------------------------------------------------------
  -- VERSIONING RULE:
  -- WHEN INSERTING A NEW RECORD, MAKE IT ACTIVE AND DEACTIVATE OTHERS
  ---------------------------------------------------------------------
  IF INSERTING THEN
    
    -- New record is always ACTIVE
    :NEW.STATUS := 'A';
    
    -- Deactivate previous ACTIVE records for same composite key
    UPDATE UR_HOTEL_PRICE_OVERRIDE
       SET STATUS     = 'I',
           UPDATED_BY = v_user_id,
           UPDATED_ON = SYSDATE
     WHERE HOTEL_ID   = :NEW.HOTEL_ID
       AND STAY_DATE  = :NEW.STAY_DATE
       AND TYPE       = :NEW.TYPE
       AND ID        != :NEW.ID
       AND STATUS     = 'A';

    -- Audit fields
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

  ---------------------------------------------------------------------
  -- UPDATES SHOULD ALMOST NEVER BE USED HERE
  -- but we keep audit logic if something updates the row
  ---------------------------------------------------------------------
  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

END;
/
ALTER TRIGGER "TRG_UR_HOTEL_PRICE_OVERRIDE_BI_TRG" ENABLE;

  ALTER TABLE "UR_HOTEL_RESERVATIONS" ADD CONSTRAINT "FK_UR_HOTEL_RESERVATIONS_HOTEL" FOREIGN KEY ("HOTEL_ID")
	  REFERENCES "UR_HOTELS" ("ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_RESERVATIONS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_RESERVATIONS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_RESERVATIONS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_ROOM_TYPES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_ROOM_TYPES
FOR EACH ROW
DECLARE
    v_current_user RAW(16);
BEGIN
  -- The following line is problematic in a row-level trigger and should generally be avoided.
  -- Date columns store date and time internally, the format is for display.
  -- execute immediate q'[alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS']';

  IF :NEW.ROOM_TYPE_ID IS NULL THEN
    -- Assign a new GUID if ROOM_TYPE_ID is null (for new records typically)
    :NEW.ROOM_TYPE_ID := SYS_GUID();
  END IF;

  IF INSERTING THEN
    
    SELECT USER_ID INTO :NEW.CREATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.CREATED_ON := SYSDATE;
    -- For new records, UPDATED_BY and UPDATED_ON are also set initially.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  IF UPDATING THEN
    -- When updating an existing record, update UPDATED_BY and UPDATED_ON.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_ROOM_TYPES_BI_TRG" ENABLE;

  ALTER TABLE "UR_INTERFACE_LOGS" ADD CONSTRAINT "FK_UR_INTERFACE_LOGS_HOTEL" FOREIGN KEY ("HOTEL_ID")
	  REFERENCES "UR_HOTELS" ("ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_INTERFACE_LOGS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_INTERFACE_LOGS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_INTERFACE_LOGS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_REPORTS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_REPORTS_BI_TRG" ENABLE;

  ALTER TABLE "UR_REPORT_DASHBOARDS" ADD CONSTRAINT "FK_UR_REPORTS_HOTEL" FOREIGN KEY ("HOTEL_ID")
	  REFERENCES "UR_HOTELS" ("ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_REPORT_DASHBOARDS_BI" 
BEFORE INSERT OR UPDATE ON UR_REPORT_DASHBOARDS
FOR EACH ROW
DECLARE
  v_hotel_name VARCHAR2(100);
  v_key_candidate VARCHAR2(110);
  v_user_id RAW(16);
  v_json_error EXCEPTION;
  PRAGMA EXCEPTION_INIT(v_json_error, -22827); -- ORA-22827 JSON parse error code
  
BEGIN
  -- Set ID if NULL
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Default CREATED_BY, UPDATED_BY, CREATED_ON, UPDATED_ON depending on insert/update
  IF INSERTING THEN

    -- Fetch CURRENT USER ID from UR_USERS via APEX user
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.CREATED_BY := v_user_id;
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20001, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_ON := SYSDATE;

    -- ACTIVE default
    IF :NEW.ACTIVE IS NULL THEN
      :NEW.ACTIVE := 'Y';
    END IF;

    -- If HOTEL_ID is provided and Name/Key are NULL or empty, derive from Hotel's name
    IF :NEW.HOTEL_ID IS NOT NULL THEN
      SELECT HOTEL_NAME INTO v_hotel_name FROM UR_HOTELS WHERE ID = :NEW.HOTEL_ID;

      -- Populate NAME if empty
      IF :NEW.NAME IS NULL OR TRIM(:NEW.NAME) = '' THEN
        :NEW.NAME := v_hotel_name;
      END IF;

      -- Populate KEY if empty
      IF :NEW."KEY" IS NULL OR TRIM(:NEW."KEY") = '' THEN
        -- Derive KEY from hotel name (uppercase, replace spaces with underscore, remove special chars except _)
        v_key_candidate := REGEXP_REPLACE(UPPER(v_hotel_name), '[^A-Z0-9_]', '');
        v_key_candidate := REPLACE(v_key_candidate, ' ', '_');  -- Redundant after regex but keep for clarity

        -- Append '_DASHBOARD' suffix if not already present
        IF NOT v_key_candidate LIKE '%_DASHBOARD' THEN
          v_key_candidate := v_key_candidate || '_DASHBOARD';
        END IF;

        :NEW."KEY" := v_key_candidate;
      END IF;
    END IF;

  ELSIF UPDATING THEN

    -- Refresh UPDATED_BY and UPDATED_ON regardless
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20002, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  -- Validate DEFINITION is valid JSON - raise error if not
  BEGIN
    -- Attempt to parse JSON in DEFINITION by wrapping in JSON_EXISTS which fails if invalid
    IF NOT JSON_EXISTS(:NEW.DEFINITION, '$') THEN
      RAISE_APPLICATION_ERROR(-20003, 'Definition column contains invalid JSON data.');
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20004, 'Definition column contains invalid JSON data.');
  END;

END;
/
ALTER TRIGGER "TRG_UR_REPORT_DASHBOARDS_BI" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_TEMPLATES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_TEMPLATES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_TEMPLATES_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_USERS_BI_TRG" 
FOR INSERT OR UPDATE ON ur_users
COMPOUND TRIGGER

  BEFORE EACH ROW IS
    l_current_user_id UR_USERS.USER_ID%TYPE;
  BEGIN
    IF INSERTING THEN
      -- generate PK if not provided
      IF :NEW.user_id IS NULL THEN
        :NEW.user_id := SYS_GUID();
      END IF;

      -- set created_by / updated_by from session package (if available)
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.created_by := l_current_user_id;
        :NEW.updated_by := l_current_user_id;
      END IF;

      -- timestamps (respect any pre-filled created_on)
      IF :NEW.created_on IS NULL THEN
        :NEW.created_on := SYSDATE;
      END IF;
      :NEW.updated_on := SYSDATE;

    ELSIF UPDATING THEN
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.updated_by := l_current_user_id;
      END IF;
      :NEW.updated_on := SYSDATE;
    END IF;
  END BEFORE EACH ROW;

END trg_ur_users_bi_trg;
/
ALTER TRIGGER "TRG_UR_USERS_BI_TRG" ENABLE;

  CREATE UNIQUE INDEX "PK_UR_HOTEL_ROOM_TYPES" ON "UR_HOTEL_ROOM_TYPES" ("ROOM_TYPE_ID") 
  ;

  CREATE UNIQUE INDEX "UK_UR_ALGO_VERSIONS_ALGO_VERSION" ON "UR_ALGO_VERSIONS" ("ALGO_ID", "VERSION") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_REPORT_DASHBOARDS_KEY" ON "UR_REPORT_DASHBOARDS" ("KEY") 
  ;

  CREATE UNIQUE INDEX "XXPEL_WF_GLOBAL_PROFILES_TBL_PK" ON "XXPEL_WF_GLOBAL_PROFILES_TBL" ("ID") 
  ;

  CREATE UNIQUE INDEX "UK_UR_ALGO_ATTRIBUTES_KEY" ON "UR_ALGO_ATTRIBUTES" ("KEY") 
  ;

  CREATE UNIQUE INDEX "PK_UR_INTERFACE_LOGS" ON "UR_INTERFACE_LOGS" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_HOTEL_GROUPS_NAME" ON "UR_HOTEL_GROUPS" ("GROUP_NAME") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_REPORTS_KEY" ON "UR_REPORTS" ("KEY") 
  ;

  CREATE UNIQUE INDEX "PK_UR_HOTEL_GROUPS" ON "UR_HOTEL_GROUPS" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_REPORT_DASHBOARDS_NAME" ON "UR_REPORT_DASHBOARDS" ("NAME") 
  ;

  CREATE UNIQUE INDEX "PK_UR_HOTEL_ACCESSES" ON "UR_HOTEL_ACCESSES" ("HOTEL_ID", "USER_ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_REPORTS" ON "UR_REPORTS" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_ALGOS" ON "UR_ALGOS" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_ALGO_ATTRIBUTES" ON "UR_ALGO_ATTRIBUTES" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_CONTACTS" ON "UR_CONTACTS" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_HOTEL_RES_UNIQUE_NUMBER" ON "UR_HOTEL_RESERVATIONS" ("HOTEL_ID", "RES_NUMBER") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_PROFILE_OPTIONS_KEY" ON "UR_PROFILE_OPTIONS" ("KEY") 
  ;

  CREATE UNIQUE INDEX "PK_UR_HOTELS" ON "UR_HOTELS" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_TEMPLATES" ON "UR_TEMPLATES" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_USERS" ON "UR_USERS" ("USER_ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_EVENTS" ON "UR_EVENTS" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_HOTEL_RESERVATIONS" ON "UR_HOTEL_RESERVATIONS" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_REPORT_DASHBOARDS" ON "UR_REPORT_DASHBOARDS" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_TEMPLATES_KEY" ON "UR_TEMPLATES" ("KEY") 
  ;

  CREATE UNIQUE INDEX "PK_ADDRESSES" ON "UR_ADDRESSES" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_REPORT_DASHBOARDS_HOTEL_ID" ON "UR_REPORT_DASHBOARDS" ("HOTEL_ID") 
  ;

  CREATE UNIQUE INDEX "PK_TEMP_BLOB" ON "TEMP_BLOB" ("ID") 
  ;

  CREATE UNIQUE INDEX "PK_UR_PROFILE_OPTIONS" ON "UR_PROFILE_OPTIONS" ("ID") 
  ;

  CREATE UNIQUE INDEX "UQ_UR_USERS_EMAIL" ON "UR_USERS" ("EMAIL") 
  ;

  CREATE UNIQUE INDEX "PK_UR_ALGO_VERSIONS" ON "UR_ALGO_VERSIONS" ("ID") 
  ;
















































create or replace TRIGGER "TRG_UR_ADDRESSES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_ADDRESSES
FOR EACH ROW
DECLARE
    v_current_user RAW(16);
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO v_current_user FROM UR_USERS WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
        :NEW.CREATED_BY := v_current_user;
        :NEW.CREATED_ON := SYSDATE;

        :NEW.UPDATED_BY := v_current_user;
        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO v_current_user FROM UR_USERS WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
        :NEW.UPDATED_BY := v_current_user;
        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_ALGOS_BI_TRG"
BEFORE INSERT OR UPDATE ON "UR_ALGOS"
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch user_id from UR_USERS based on APEX session user
  SELECT USER_ID INTO v_user_id 
    FROM UR_USERS
   WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  IF INSERTING THEN
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  END IF;
END;
/
create or replace TRIGGER "TRG_UR_ALGO_ATTRIBUTES_BI_TRG"
BEFORE INSERT OR UPDATE ON "UR_ALGO_ATTRIBUTES"
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch USER_ID from UR_USERS based on APEX session user
  SELECT USER_ID INTO v_user_id
    FROM UR_USERS
   WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  IF INSERTING THEN
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

    -- Set default DATA_TYPE if null
    IF :NEW.DATA_TYPE IS NULL THEN
      :NEW.DATA_TYPE := 'NUMBER';
    END IF;

    -- Set default TYPE if null
    IF :NEW.TYPE IS NULL THEN
      :NEW.TYPE := 'M';
    END IF;

    -- Automatically generate KEY from NAME using UR_UTILS.Clean_TEXT if KEY is null or empty
    IF :NEW.KEY IS NULL OR TRIM(:NEW.KEY) = '' THEN
      :NEW.KEY := UR_UTILS.Clean_TEXT(:NEW.NAME);
    END IF;

  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

    -- Do NOT modify KEY during update, leave as is

    -- Ensure DATA_TYPE defaults if null
    IF :NEW.DATA_TYPE IS NULL THEN
      :NEW.DATA_TYPE := 'NUMBER';
    END IF;

    -- Ensure TYPE defaults if null
    IF :NEW.TYPE IS NULL THEN
      :NEW.TYPE := 'M';
    END IF;

  END IF;
END;
/
create or replace TRIGGER TRG_UR_ALGO_VERSIONS_BI_TRG
BEFORE INSERT OR UPDATE ON UR_ALGO_VERSIONS
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
  v_max_version NUMBER;
  v_new_version NUMBER;
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch user_id from UR_USERS based on APEX session user
  SELECT USER_ID INTO v_user_id
  FROM UR_USERS
  WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  IF INSERTING THEN
    -- Set audit columns
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

    -- Auto increment VERSION
    BEGIN
      SELECT MAX(TO_NUMBER(VERSION)) INTO v_max_version
      FROM UR_ALGO_VERSIONS
      WHERE ALGO_ID = :NEW.ALGO_ID;

      v_new_version := NVL(v_max_version, 0) + 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_new_version := 1;
      WHEN VALUE_ERROR THEN
        -- version column has non-numeric values - fallback to 1
        v_new_version := 1;
    END;
    :NEW.VERSION := TO_CHAR(v_new_version);

  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  -- Update UR_ALGOS table CURRENT_VERSION_ID to the VERSION record ID that was just inserted/updated
  UPDATE UR_ALGOS
  SET CURRENT_VERSION_ID = :NEW.ID,
      UPDATED_BY = v_user_id,
      UPDATED_ON = SYSDATE
  WHERE ID = :NEW.ALGO_ID;

END;
/
create or replace TRIGGER TRG_UR_CONTACTS_BI_TRG
BEFORE INSERT OR UPDATE ON UR_CONTACTS
FOR EACH ROW
DECLARE
    v_user_id RAW(16);
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    BEGIN
        SELECT USER_ID INTO v_user_id
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_user_id := SYS_GUID();
    END;

    IF INSERTING THEN
        :NEW.CREATED_BY := v_user_id;
        :NEW.CREATED_ON := SYSDATE;
        :NEW.UPDATED_BY := v_user_id;
        :NEW.UPDATED_ON := SYSDATE;
    ELSIF UPDATING THEN
        :NEW.UPDATED_BY := v_user_id;
        :NEW.UPDATED_ON := SYSDATE;
    END IF;

END;
/
create or replace TRIGGER "TRG_UR_EVENTS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_EVENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        -- Assign a new GUID if EVENT_ID is null (typical on insert)
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY 
        FROM UR_USERS 
        WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY 
        FROM UR_USERS 
        WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY 
        FROM UR_USERS 
        WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_HOTELS_BI_TRG"
BEFORE INSERT OR UPDATE ON UR_HOTELS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

        IF :NEW.CURRENCY_CODE IS NULL THEN
            :NEW.CURRENCY_CODE := 'GBP';
        END IF;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_HOTEL_GROUPS_BI_TRG"
BEFORE INSERT OR UPDATE ON UR_HOTEL_GROUPS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_HOTEL_PRICE_OVERRIDE_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_PRICE_OVERRIDE
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
BEGIN
  -- Assign GUID if missing
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch user_id from UR_USERS using APEX user
  SELECT USER_ID 
    INTO v_user_id 
    FROM UR_USERS
   WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  ---------------------------------------------------------------------
  -- VERSIONING RULE:
  -- WHEN INSERTING A NEW RECORD, MAKE IT ACTIVE AND DEACTIVATE OTHERS
  ---------------------------------------------------------------------
  IF INSERTING THEN
    
    -- New record is always ACTIVE
    :NEW.STATUS := 'A';
    
    -- Deactivate previous ACTIVE records for same composite key
    UPDATE UR_HOTEL_PRICE_OVERRIDE
       SET STATUS     = 'I',
           UPDATED_BY = v_user_id,
           UPDATED_ON = SYSDATE
     WHERE HOTEL_ID   = :NEW.HOTEL_ID
       AND STAY_DATE  = :NEW.STAY_DATE
       AND TYPE       = :NEW.TYPE
       AND ID        != :NEW.ID
       AND STATUS     = 'A';

    -- Audit fields
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

  ---------------------------------------------------------------------
  -- UPDATES SHOULD ALMOST NEVER BE USED HERE
  -- but we keep audit logic if something updates the row
  ---------------------------------------------------------------------
  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

END;
/
create or replace TRIGGER "TRG_UR_HOTEL_RESERVATIONS_BI_TRG"
BEFORE INSERT OR UPDATE ON UR_HOTEL_RESERVATIONS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_HOTEL_ROOM_TYPES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_ROOM_TYPES
FOR EACH ROW
DECLARE
    v_current_user RAW(16);
BEGIN
  -- The following line is problematic in a row-level trigger and should generally be avoided.
  -- Date columns store date and time internally, the format is for display.
  -- execute immediate q'[alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS']';

  IF :NEW.ROOM_TYPE_ID IS NULL THEN
    -- Assign a new GUID if ROOM_TYPE_ID is null (for new records typically)
    :NEW.ROOM_TYPE_ID := SYS_GUID();
  END IF;

  IF INSERTING THEN
    
    SELECT USER_ID INTO :NEW.CREATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.CREATED_ON := SYSDATE;
    -- For new records, UPDATED_BY and UPDATED_ON are also set initially.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  IF UPDATING THEN
    -- When updating an existing record, update UPDATED_BY and UPDATED_ON.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;
END;
/
create or replace TRIGGER "TRG_UR_INTERFACE_LOGS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_INTERFACE_LOGS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER "TRG_UR_REPORTS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER trg_ur_report_dashboards_bi
BEFORE INSERT OR UPDATE ON UR_REPORT_DASHBOARDS
FOR EACH ROW
DECLARE
  v_hotel_name VARCHAR2(100);
  v_key_candidate VARCHAR2(110);
  v_user_id RAW(16);
  v_json_error EXCEPTION;
  PRAGMA EXCEPTION_INIT(v_json_error, -22827); -- ORA-22827 JSON parse error code
  
BEGIN
  -- Set ID if NULL
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Default CREATED_BY, UPDATED_BY, CREATED_ON, UPDATED_ON depending on insert/update
  IF INSERTING THEN

    -- Fetch CURRENT USER ID from UR_USERS via APEX user
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.CREATED_BY := v_user_id;
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20001, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_ON := SYSDATE;

    -- ACTIVE default
    IF :NEW.ACTIVE IS NULL THEN
      :NEW.ACTIVE := 'Y';
    END IF;

    -- If HOTEL_ID is provided and Name/Key are NULL or empty, derive from Hotel's name
    IF :NEW.HOTEL_ID IS NOT NULL THEN
      SELECT HOTEL_NAME INTO v_hotel_name FROM UR_HOTELS WHERE ID = :NEW.HOTEL_ID;

      -- Populate NAME if empty
      IF :NEW.NAME IS NULL OR TRIM(:NEW.NAME) = '' THEN
        :NEW.NAME := v_hotel_name;
      END IF;

      -- Populate KEY if empty
      IF :NEW."KEY" IS NULL OR TRIM(:NEW."KEY") = '' THEN
        -- Derive KEY from hotel name (uppercase, replace spaces with underscore, remove special chars except _)
        v_key_candidate := REGEXP_REPLACE(UPPER(v_hotel_name), '[^A-Z0-9_]', '');
        v_key_candidate := REPLACE(v_key_candidate, ' ', '_');  -- Redundant after regex but keep for clarity

        -- Append '_DASHBOARD' suffix if not already present
        IF NOT v_key_candidate LIKE '%_DASHBOARD' THEN
          v_key_candidate := v_key_candidate || '_DASHBOARD';
        END IF;

        :NEW."KEY" := v_key_candidate;
      END IF;
    END IF;

  ELSIF UPDATING THEN

    -- Refresh UPDATED_BY and UPDATED_ON regardless
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20002, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  -- Validate DEFINITION is valid JSON - raise error if not
  BEGIN
    -- Attempt to parse JSON in DEFINITION by wrapping in JSON_EXISTS which fails if invalid
    IF NOT JSON_EXISTS(:NEW.DEFINITION, '$') THEN
      RAISE_APPLICATION_ERROR(-20003, 'Definition column contains invalid JSON data.');
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20004, 'Definition column contains invalid JSON data.');
  END;

END;
/
create or replace TRIGGER "TRG_UR_TEMPLATES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_TEMPLATES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
create or replace TRIGGER trg_ur_users_bi_trg
FOR INSERT OR UPDATE ON ur_users
COMPOUND TRIGGER

  BEFORE EACH ROW IS
    l_current_user_id UR_USERS.USER_ID%TYPE;
  BEGIN
    IF INSERTING THEN
      -- generate PK if not provided
      IF :NEW.user_id IS NULL THEN
        :NEW.user_id := SYS_GUID();
      END IF;

      -- set created_by / updated_by from session package (if available)
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.created_by := l_current_user_id;
        :NEW.updated_by := l_current_user_id;
      END IF;

      -- timestamps (respect any pre-filled created_on)
      IF :NEW.created_on IS NULL THEN
        :NEW.created_on := SYSDATE;
      END IF;
      :NEW.updated_on := SYSDATE;

    ELSIF UPDATING THEN
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.updated_by := l_current_user_id;
      END IF;
      :NEW.updated_on := SYSDATE;
    END IF;
  END BEFORE EACH ROW;

END trg_ur_users_bi_trg;
/

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTELS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTELS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

        IF :NEW.CURRENCY_CODE IS NULL THEN
            :NEW.CURRENCY_CODE := 'GBP';
        END IF;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTELS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_GROUPS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_GROUPS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_GROUPS_BI_TRG" ENABLE;

   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."ID" IS 'UUID - Unique attribute identifier (Primary Key).';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."STAY_DATE" IS 'The specific date for which the price is overridden.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."HOTEL_ID" IS 'Optional Foreign Key to a Hotel table to limit the override to a specific hotel.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."TYPE" IS 'Pricing Type (e.g., Retail, Group).';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."PRICE" IS 'The overridden price for the stay date.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."REASON" IS 'Justification for the price override.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."CREATED_BY" IS 'UUID of the user who created the record.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."UPDATED_BY" IS 'UUID of the user who last updated the record.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."CREATED_ON" IS 'Timestamp of when the record was created.';
   COMMENT ON COLUMN "UR_HOTEL_PRICE_OVERRIDE"."UPDATED_ON" IS 'Timestamp of when the record was last updated.';
   COMMENT ON TABLE "UR_HOTEL_PRICE_OVERRIDE"  IS 'Stores daily price overrides for hotels.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_PRICE_OVERRIDE_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_PRICE_OVERRIDE
FOR EACH ROW
DECLARE
  v_user_id RAW(16);
BEGIN
  -- Assign GUID if missing
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Fetch user_id from UR_USERS using APEX user
  SELECT USER_ID 
    INTO v_user_id 
    FROM UR_USERS
   WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

  ---------------------------------------------------------------------
  -- VERSIONING RULE:
  -- WHEN INSERTING A NEW RECORD, MAKE IT ACTIVE AND DEACTIVATE OTHERS
  ---------------------------------------------------------------------
  IF INSERTING THEN
    
    -- New record is always ACTIVE
    :NEW.STATUS := 'A';
    
    -- Deactivate previous ACTIVE records for same composite key
    UPDATE UR_HOTEL_PRICE_OVERRIDE
       SET STATUS     = 'I',
           UPDATED_BY = v_user_id,
           UPDATED_ON = SYSDATE
     WHERE HOTEL_ID   = :NEW.HOTEL_ID
       AND STAY_DATE  = :NEW.STAY_DATE
       AND TYPE       = :NEW.TYPE
       AND ID        != :NEW.ID
       AND STATUS     = 'A';

    -- Audit fields
    :NEW.CREATED_BY := v_user_id;
    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;

  ---------------------------------------------------------------------
  -- UPDATES SHOULD ALMOST NEVER BE USED HERE
  -- but we keep audit logic if something updates the row
  ---------------------------------------------------------------------
  ELSIF UPDATING THEN
    :NEW.UPDATED_BY := v_user_id;
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

END;
/
ALTER TRIGGER "TRG_UR_HOTEL_PRICE_OVERRIDE_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_RESERVATIONS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_RESERVATIONS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_RESERVATIONS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_HOTEL_ROOM_TYPES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_HOTEL_ROOM_TYPES
FOR EACH ROW
DECLARE
    v_current_user RAW(16);
BEGIN
  -- The following line is problematic in a row-level trigger and should generally be avoided.
  -- Date columns store date and time internally, the format is for display.
  -- execute immediate q'[alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS']';

  IF :NEW.ROOM_TYPE_ID IS NULL THEN
    -- Assign a new GUID if ROOM_TYPE_ID is null (for new records typically)
    :NEW.ROOM_TYPE_ID := SYS_GUID();
  END IF;

  IF INSERTING THEN
    
    SELECT USER_ID INTO :NEW.CREATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.CREATED_ON := SYSDATE;
    -- For new records, UPDATED_BY and UPDATED_ON are also set initially.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  IF UPDATING THEN
    -- When updating an existing record, update UPDATED_BY and UPDATED_ON.
    SELECT USER_ID INTO :NEW.UPDATED_BY FROM UR_USERS WHERE USER_NAME = (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'));
    :NEW.UPDATED_ON := SYSDATE;
  END IF;
END;
/
ALTER TRIGGER "TRG_UR_HOTEL_ROOM_TYPES_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_INTERFACE_LOGS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_INTERFACE_LOGS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_INTERFACE_LOGS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_REPORTS_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_REPORTS_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_REPORT_DASHBOARDS_BI" 
BEFORE INSERT OR UPDATE ON UR_REPORT_DASHBOARDS
FOR EACH ROW
DECLARE
  v_hotel_name VARCHAR2(100);
  v_key_candidate VARCHAR2(110);
  v_user_id RAW(16);
  v_json_error EXCEPTION;
  PRAGMA EXCEPTION_INIT(v_json_error, -22827); -- ORA-22827 JSON parse error code
  
BEGIN
  -- Set ID if NULL
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SYS_GUID();
  END IF;

  -- Default CREATED_BY, UPDATED_BY, CREATED_ON, UPDATED_ON depending on insert/update
  IF INSERTING THEN

    -- Fetch CURRENT USER ID from UR_USERS via APEX user
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.CREATED_BY := v_user_id;
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20001, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.CREATED_ON := SYSDATE;
    :NEW.UPDATED_ON := SYSDATE;

    -- ACTIVE default
    IF :NEW.ACTIVE IS NULL THEN
      :NEW.ACTIVE := 'Y';
    END IF;

    -- If HOTEL_ID is provided and Name/Key are NULL or empty, derive from Hotel's name
    IF :NEW.HOTEL_ID IS NOT NULL THEN
      SELECT HOTEL_NAME INTO v_hotel_name FROM UR_HOTELS WHERE ID = :NEW.HOTEL_ID;

      -- Populate NAME if empty
      IF :NEW.NAME IS NULL OR TRIM(:NEW.NAME) = '' THEN
        :NEW.NAME := v_hotel_name;
      END IF;

      -- Populate KEY if empty
      IF :NEW."KEY" IS NULL OR TRIM(:NEW."KEY") = '' THEN
        -- Derive KEY from hotel name (uppercase, replace spaces with underscore, remove special chars except _)
        v_key_candidate := REGEXP_REPLACE(UPPER(v_hotel_name), '[^A-Z0-9_]', '');
        v_key_candidate := REPLACE(v_key_candidate, ' ', '_');  -- Redundant after regex but keep for clarity

        -- Append '_DASHBOARD' suffix if not already present
        IF NOT v_key_candidate LIKE '%_DASHBOARD' THEN
          v_key_candidate := v_key_candidate || '_DASHBOARD';
        END IF;

        :NEW."KEY" := v_key_candidate;
      END IF;
    END IF;

  ELSIF UPDATING THEN

    -- Refresh UPDATED_BY and UPDATED_ON regardless
    BEGIN
      SELECT USER_ID INTO v_user_id
      FROM UR_USERS
      WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        v_user_id := NULL;
    END;

    IF v_user_id IS NOT NULL THEN
      :NEW.UPDATED_BY := v_user_id;
    ELSE
      RAISE_APPLICATION_ERROR(-20002, 'Unable to find USER_ID for current APEX user');
    END IF;

    :NEW.UPDATED_ON := SYSDATE;
  END IF;

  -- Validate DEFINITION is valid JSON - raise error if not
  BEGIN
    -- Attempt to parse JSON in DEFINITION by wrapping in JSON_EXISTS which fails if invalid
    IF NOT JSON_EXISTS(:NEW.DEFINITION, '$') THEN
      RAISE_APPLICATION_ERROR(-20003, 'Definition column contains invalid JSON data.');
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20004, 'Definition column contains invalid JSON data.');
  END;

END;
/
ALTER TRIGGER "TRG_UR_REPORT_DASHBOARDS_BI" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_TEMPLATES_BI_TRG" 
BEFORE INSERT OR UPDATE ON UR_TEMPLATES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SYS_GUID();
    END IF;

    IF INSERTING THEN
        SELECT USER_ID INTO :NEW.CREATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.CREATED_ON := SYSDATE;

        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;

    ELSIF UPDATING THEN
        SELECT USER_ID INTO :NEW.UPDATED_BY
          FROM UR_USERS
         WHERE USER_NAME = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        :NEW.UPDATED_ON := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "TRG_UR_TEMPLATES_BI_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_UR_USERS_BI_TRG" 
FOR INSERT OR UPDATE ON ur_users
COMPOUND TRIGGER

  BEFORE EACH ROW IS
    l_current_user_id UR_USERS.USER_ID%TYPE;
  BEGIN
    IF INSERTING THEN
      -- generate PK if not provided
      IF :NEW.user_id IS NULL THEN
        :NEW.user_id := SYS_GUID();
      END IF;

      -- set created_by / updated_by from session package (if available)
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.created_by := l_current_user_id;
        :NEW.updated_by := l_current_user_id;
      END IF;

      -- timestamps (respect any pre-filled created_on)
      IF :NEW.created_on IS NULL THEN
        :NEW.created_on := SYSDATE;
      END IF;
      :NEW.updated_on := SYSDATE;

    ELSIF UPDATING THEN
      l_current_user_id := app_user_ctx.get_current_user_id;
      IF l_current_user_id IS NOT NULL THEN
        :NEW.updated_by := l_current_user_id;
      END IF;
      :NEW.updated_on := SYSDATE;
    END IF;
  END BEFORE EACH ROW;

END trg_ur_users_bi_trg;
/
ALTER TRIGGER "TRG_UR_USERS_BI_TRG" ENABLE; 